# Assetic config
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    #node: "%path_to_node%"
    filters:
        cssrewrite: ~
        jsqueeze: ~
        #uglifyjs2:
        #    bin: "%path_to_uglifyjs%"
        #uglifycss:
        #    bin: "%path_to_uglifycss%"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
    bundles:
        - FpJsFormValidatorBundle
        - AppBundle
        - FOSUserBundle
        - XBundle

a2lix_translation_form:
  locale_provider: default
  locales: "%locales%"
  default_locale : "%locale%"
  required_locales: ["%locale%"]
  templating: "A2lixTranslationFormBundle::default.html.twig"

tetranz_select2_entity:
    minimum_input_length: 0
    page_limit: 8
    allow_clear: false
    delay: 500
    language: "%locale%"
    cache: false
    cache_timeout: 0
    scroll: false

oneup_uploader:
    mappings:
        artist_gallery:
            frontend: dropzone # or any uploader you use in the frontend
            namer: AppBundle\Services\ArtistPhotoUploadNamer
        hall_gallery:
            frontend: dropzone
            namer: AppBundle\Services\HallPhotoUploadNamer
        yb_campaign:
            frontend: dropzone
            namer: AppBundle\Services\YBContractArtistPhotoUploadNamer
            storage:
              directory: "%kernel.root_dir%/../web/yb/images/campaigns/"
        x_project:
            frontend: dropzone
            namer: XBundle\Services\ProjectPhotoUploadNamer
            storage:
              directory: '%kernel.root_dir%/../web/x/images/projects'

vich_uploader:
    db_driver: orm
    mappings:
      hall_technical_specs:
          uri_prefix:         uploads/hall_technicalspecs
          upload_destination: '%kernel.root_dir%/../web/uploads/hall_technicalspecs'
          delete_on_update:   true
          delete_on_remove:   true
          inject_on_load:     false
          namer:
            service: AppBundle\Services\BySlugNamer
      yb_campaign_header:
          uri_prefix:         yb/images/campaigns
          upload_destination: '%kernel.root_dir%/../web/yb/images/campaigns'
          delete_on_update: true
          delete_on_remove: true
          inject_on_load: true
          namer:
            service: AppBundle\Services\UniqIdNamer
      yb_venue_header:
          uri_prefix:         yb/images/venues
          upload_destination: '%kernel.root_dir%/../web/yb/images/venues'
          delete_on_update: true
          delete_on_remove: true
          inject_on_load: true
          namer:
            service: AppBundle\Services\UniqIdNamer
      yb_organization_header:
          uri_prefix:         yb/images/organizations
          upload_destination: '%kernel.root_dir%/../web/yb/images/organizations'
          delete_on_update: true
          delete_on_remove: true
          inject_on_load: true
          namer:
            service: AppBundle\Services\UniqIdNamer
      x_project_header:
          uri_prefix:         x/images/projects
          upload_destination: '%kernel.root_dir%/../web/x/images/projects'
          delete_on_update: true
          delete_on_remove: true
          inject_on_load: true
          namer:
            service: AppBundle\Services\UniqIdNamer
      x_product_header:
        uri_prefix:         x/images/products
        upload_destination: '%kernel.root_dir%/../web/x/images/products'
        delete_on_update: true
        delete_on_remove: true
        inject_on_load: true
        namer:
          service: AppBundle\Services\UniqIdNamer
      x_choice_option_header:
        uri_prefix:         x/images/products/choices
        upload_destination: '%kernel.root_dir%/../web/x/images/products/choices'
        delete_on_update: true
        delete_on_remove: true
        inject_on_load: true
        namer:
          service: AppBundle\Services\UniqIdNamer

jmose_command_scheduler:
    log_path: '%kernel.root_dir%/../var/logs/commands/'

cspoo_swiftmailer_mailgun:
    key: "%mailgun_api_secret%"
    domain: "%mailgun_domain%"
    http_client: ~ # Optional. Defaults to null and uses discovery to find client.

services:
    yb_contract_artist_flow:
      class: AppBundle\Form\YB\YBContractArtistType
      parent: craue.form.flow

nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/':
                origin_regex: true
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']