# app/config/routing.yml
app_all:
    resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

azine_email_bundle:
    resource: "@AzineEmailBundle/Resources/config/routing.yml"
    prefix: /mail

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app_select2:
  resource: "@AppBundle/Controller/Select2Controller.php"
  type: annotation
  prefix: /select2

oneup_uploader:
  resource: .
  type: uploader

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /

fp_js_form_validator:
    resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
    prefix: /fp_js_form_validator
