# app/config/routing.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

azine_email_bundle:
    resource: "@AzineEmailBundle/Resources/config/routing.yml"
    prefix: /mail

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app_sec:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation
    prefix: /secure

app_select2:
  resource: "@AppBundle/Controller/Select2Controller.php"
  type: annotation
  prefix: /select2

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /

app_all:
    resource: "@AppBundle/Resources/config/routing.yml"

