yb_controller:
  resource: "@AppBundle/Controller/YBController.php"
  type: annotation
  schemes: ['%http_protocol%']
  prefix: /

yb_members_controller:
  resource: "@AppBundle/Controller/YBMembersController.php"
  type: annotation
  schemes: ['%http_protocol%']
  prefix: /edit

fos_user_security_check_yb:
  path: "/login_check"
  methods: ["POST"]
  host: "%yb_host%"
  defaults:
    _controller: fos_user.security.controller:checkAction