# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:               ROLE_FAN, ROLE_SONATA_ADMIN
        ROLE_PAYMENTS_ADMIN:      ROLE_ADMIN
        ROLE_TRANSLATIONS_ADMIN:  ROLE_ADMIN
        ROLE_SUPER_ADMIN:         ROLE_PAYMENTS_ADMIN, ROLE_TRANSLATIONS_ADMIN
        ROLE_FAN:                 ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email # authorize login by e-mail

    firewalls:
        main:
            remember_me:
                secret:   '%secret%'
                lifetime: 2419200 # 4 weeks in seconds
                name: '%session.remember_me.name%'
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: homepage
                failure_path: fos_user_security_login
                #csrf_parameter:       _csrf_token
                #csrf_token_id:        authenticate
                #csrf_token_generator: security.csrf.token_manager
                use_referer: true
                require_previous_session: false
            oauth:
              resource_owners:
                facebook:           "/login/check-facebook"
              login_path:        fos_user_security_login
              failure_path:      fos_user_security_login

              oauth_user_provider:
                  #this is my custom user provider, created from FOSUBUserProvider - will manage the
                  #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                  service:  um_fosub_user_provider
            logout:
              path: /logout
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/, role: ROLE_ADMIN }
        - { path: ^/command-scheduler/, role: ROLE_ADMIN }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
