# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # Apparently needed for Symfony 3.3.6 to work...
    resolve_controller_name_subscriber:
      public: true
      abstract: true

    console.error_listener:
      public: true
      abstract: true

    # The following line blocks an error in the AzineEmailBundle which references a non-existent "immediatemailer" service
    swiftmailer.mailer.immediatemailer: "@mailer"

    # Defaults, which will allow Symfony to use autowiring and autoconfiguring
    _defaults:
        autowire: true # automatically injects dependencies in the
        autoconfigure: true # automatically registers services as commands, event subscribers, etc.
        public: true

    # Registration
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    AppBundle\EventListener\UploadListener:
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    AppBundle\Services: ~

    AppBundle\Services\MailDispatcher:
      arguments:
        $from_address: "%mailer_from_address%"
        $from_name: "%mailer_from_name%"

    AppBundle\Form\ContractArtistFlow:
      parent: craue.form.flow
      autowire: true
      autoconfigure: false
      public: true