# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # Avoid deprecation for private service
    swiftmailer.transport.real:
      public: true
      abstract: true

    # Apparently needed for Symfony 3.3.6 to work...
    resolve_controller_name_subscriber:
      public: true
      abstract: true
    console.error_listener:
      public: true
      abstract: true

    # The following line blocks an error in the AzineEmailBundle which references a non-existent "immediatemailer" service
    swiftmailer.mailer.immediatemailer: "@mailer"

    # Defaults, which will allow Symfony to use autowiring and autoconfiguring
    _defaults:
        autowire: true # automatically injects dependencies in the
        autoconfigure: true # automatically registers services as commands, event subscribers, etc.
        public: true

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']
    
    XBundle\Controller\:
        resource: '../../src/XBundle/Controller'
        tags: ['controller.service_arguments']

    # Registration
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.changepassword:
      class: AppBundle\Form\ChangePasswordType
      calls:
        - method: setUser
          arguments:
            - '@security.token_storage'

    AppBundle\Connect\UMFOSUBUserProvider:
      arguments: ['@fos_user.user_manager',{facebook: facebook_id}]
      calls:
        - method: setLogger
          arguments:
            - '@logger'
        - method: setEventDispatcher
          arguments:
            - '@event_dispatcher'
        - method: setRequest
          arguments:
            - '@request_stack'

    um_fosub_user_provider: '@AppBundle\Connect\UMFOSUBUserProvider'

    AppBundle\EventListener\UploadListener:
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    AppBundle\EventListener\ChangePasswordListener:
      tags:
        - {name: kernel.event_subscriber }

    AppBundle\EventListener\ConnectListener:
      tags:
        - {name: kernel.event_subscriber }

    AppBundle\EventListener\KernelListener:
      arguments:
        $session_name: '%session.name%'
        $remember_me_name: '%session.remember_me.name%'
      tags:
        - {name: kernel.event_subscriber }

    AppBundle\Services\:
      resource: '../../src/AppBundle/Services/*'

    AppBundle\Services\MailDispatcher:
      arguments:
        $from_address: "%mailer_from_address%"
        $from_name: "%mailer_from_name%"
        $locales: "%locales%"

    AppBundle\Services\UserRolesManager:
      arguments:
        $hierarchy: "%security.role_hierarchy.roles%"
    user_roles_manager: '@AppBundle\Services\UserRolesManager'

    AppBundle\Services\PaymentManager:
      arguments:
        $stripe_api_secret: "%stripe_api_secret%"

    AppBundle\Services\CaptchaManager:
      arguments:
        $google_captcha_api_secret: "%google_captcha_api_secret%"