services:
#    x.example:
#        class: XBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    x.form.type.tags:
      class: XBundle\Form\TagType
      arguments: ['@doctrine.orm.entity_manager']
      tags:
        - { name: form.type }
