app_public:
    resource: "@AppBundle/Controller/PublicController.php"
    type:     annotation

app_anonymous:
    resource: "@AppBundle/Controller/AnonymousActionsController.php"
    type: annotation

app_sponsorshop:
    resource: "@AppBundle/Controller/SponsorshipController.php"
    type: annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix: /

app_artist:
    resource: "@AppBundle/Controller/ArtistController.php"
    type:     annotation
    prefix: /artist/{id}

app_payment:
    resource: "@AppBundle/Controller/PaymentController.php"
    type:     annotation
    prefix: /secure-zone

app_ticketing:
    resource: "@AppBundle/Controller/TicketingController.php"
    type:     annotation
    prefix:   /ticketing

app_conditions:
    resource: "@AppBundle/Controller/ConditionsController.php"
    type:     annotation
    prefix:   /conditions

app_webhooks:
    resource: "@AppBundle/Controller/WebHooksController.php"
    type:     annotation
    prefix: /wh/
